assaf/zombie

- README.md
Just a simple tweak to the README.
> Added mention of Browser.debug() way of enabled debugging to README.

- src/dom/forms.js
- test/forms_test.js
Change so that `<form><input type="image" name="NAME"></form>` submits `NAME.x` and
`NAME.y`. If there is no value, following at least what Chrome does, `NAME`
is not submitted at all.
See https://html.spec.whatwg.org/multipage/forms.html#image-button-state-(type=image)
and also https://bugzilla.mozilla.org/show_bug.cgi?id=583211
Fixes #685
> Fix #865 form submit for type="image".

- src/assert.js
- src/document.js
- src/dom/jsdom_patches.js
- src/index.js
- src/resources.js
- src/xhr.js
- test/history_test.js
- test/jsdom_patches_test.js
This test case was broken on Linux running from a path containing an upper case letter. I may be missing something, but I'm not sure why it would be desirable to convert the path to lower case on any platform.
> Fix file path in test case.

- src/assert.js
- test/assert_test.js
`assert.elements` did nothing when the value passed was `0`, making a few other tests noop. (e.g. https://github.com/assaf/zombie/blob/master/test/forms_test.js#L427)
The issue was `if (count.exactly)` evaluating to false when `count.exactly` was 0. Same goes for `count.atLeast` and `count.atMost`.
I fixed the issue and added a few tests including the `count.exactly = 0` case.
> Fix assert.elements bug.

- package.json
To work around `_regeneratorRuntime.awrap is not a function` errors.
If this gets merged, #921 and #922 should be updated accordingly and their
builds will probably pass.
> Upgrade Babel to upgrade Regenerator.

- src/index.js
- test/forms_test.js
This pull request is for fixing the issue #935 (wrong usage of attributes instead of properties).
> FIXED #935: using properties instead of attributes whenever possible

- src/pipeline.js
- test/resources_test.js
This method can be useful for situations when handlers need to be removed after a specific request or response has been observed, e.g.,
```javascript
var githubPromise, githubResponse;
before(function(){
githubPromise = new Promise(function(resolve, reject, response){
var requestPipelineHandler = function(browser, request){
if(request.method === 'GET' && /github\.com/.test(request.url)){
console.log('resolve github request promise');
browser.pipeline.removeHandler(requestPipelineHandler);
resolve();
githubResponse = response;
}
return response;
}
browser.pipeline.addHandler(requestPipelineHandler);
});
return browser.visit('/assaf/zombie/');
});
it('Should request Github', function(){
return githubPromise;
});
it('Should have response status of 200', function(){ …
```
> removeHandler method in Pipeline

- src/fetch.js
If you give an object to the constructor of `Headers`, <q>TypeError: Cannot read property 'append' of undefined</q> occurs.
This pull request fixes it.
```js
// Based on the sample code in https://fetch.spec.whatwg.org/#headersinit
var Headers = require('zombie').Headers;
var meta = { "Content-Type": "text/xml", "Breaking-Bad": "<3" };
new Headers(meta);
```
```
/home/vzvu3k6k/zombie/lib/fetch.js:72
this.append(name, value);
^
TypeError: Cannot read property 'append' of undefined
at /home/vzvu3k6k/zombie/lib/fetch.js:72:11
at /home/vzvu3k6k/zombie/node_modules/lodash/index.js:3073:15
at baseForOwn (/home/vzvu3k6k/zombie/node_modules/lodash/index.js:2046:14)
at /home/vzvu3k6k/zombie/node_modules/lodash/index.js:3043:18
at Function.<anonymous> …
```
> Fix `this` value in callback in constuctor of Headers

- .eslintrc
There are a few tests that use `for` loops with a single statement,
and this rule wants curly braces to be removed from such for loops.
I'm not sure what the code standard for this project is, so I went
for the simplest way to make the build pass. (On node 5.3.0).
> Treat curly rule violation as warning, not error.

- .travis.yml
- package.json
This change is needed in order to install zombie on node 5.x with
strict engine:
`npm config set engine-strict true`
All tests are passing on node 5.3.0, so I see no reason to require 4.x only.
> Relax node version

- src/fetch.js
Because of the behavior of nodejs regarding code run in vm.runInContext
method, object passed to zombie are not instance of the same Object
class. (see
https://github.com/nodejs/node/issues/4676#issuecomment-171430653)
So checking `init instanceof Object` returns `false` and no headers are
set.
This fixes https://github.com/assaf/zombie/issues/1004 
I am not sure how to test that, as I need to simulate a browser context. If you have any suggestion regarding testing, let me know
> fix adding custom headers with the browser's fetch

- src/document.js
- test/websocket_test.js
Leaving them open prevents garbage collection and can crash if
server sends a message after the window has been destroyed.
This is important for web applications that are permanently connected
to the server, for example those using Meteor framework.
> Close all WebSocket connections when leaving the page

- package.json
This PR address #1017, allowing Zombie to be installed without any compile step. No tests break as a result of the upgrade.
> Bump version of ws module

- test/browser_events_test.js
The behavior of util.format() changed when formatting errors being node v4 and v6. The new version includes the full stack trace, when node v4 only included the message.
This version of the tests can run in either node v4 or v6.
> Update console tests to account for changes in util.format

- package.json
- src/document.js
- test/websocket_test.js
This PR builds on PR #1033 to add improve compatibility with older socket.io version that have not yet adopted ws 1.x APIs. In ws 1.x, the binaryType values are checked to only allows `arraybuffer` and the node.js type, `nodebuffer`.
This change allows for comability during the period of adoption so that zombie can be used on node v6 engines with existing socket.io client versions.
> Support ws 'buffer' binaryType for socket.io compatibility

- src/index.js
- test/selection_test.js
Some button widgets (that are actually represented by a standard button) are not selectable using the `button()` helper.
The attached patch supports finding other well know button-like `<input>` elements such as `<input type="button">` and `<input type="reset">` in addition to the already supported `<input type="submit">`.
I intentionally left out from the patch the `<input type="image">`  kind because although it is technically a button, it does not present the usual button look and feel by default so it does not feel that weird not being able to locate it using `button()`
> Support other button-like input fields

- src/xhr.js
- test/xhr_test.js
Aborting an already DONE XMLHttpRequest results in a zombie.js JavaScript error:
```
Cannot set property 'aborted' of null
```
The error is caused by this line in xhr.js:
```
// Tell any pending request it has been aborted.
request.aborted = true;
```
The problem is that as the request already finished, it is set to null.
I tried to refactor the tests a little bit to reuse the `readyState` tracking code. The same code is duplicated in other places in the script but as I'm not sure if it will be positively received I did not change the other occurrences :). I would not mind sending a new pull request with that, though.
> Support aborting DONE XMLHttpRequests

- README.md
Changing reference of io.js to Node.js since it is EOL at this point.
> Remove reference to io.js

- README.md
I have had issues with node 8 and I would like to explicitly name which versions of node that zombie will work with
> Update Readme to indicate which versions of node will work

- README.md
Adding documentation to the README for `browser.source` and `browser.html`
> doc: Add documentation for browser.source and browser.html()

- src/fetch.js
- test/window_test.js
PR #1006 fixes an issue where HeadersInit is passed as an
Object from different context. This fixes array checking. Arrays passed
from a different context did not pass previous check and were recognized
as Object which caused unexpected results.
Test specs covering both Object and Array passed as HeadersInit has been
created.
This also covers and fixes #1004.
> Fetch HeadersInit as an Array fixed and tests

- src/cookies.js
Using `browser.deleteCookies()` after each visit didn't seem to clear the cookies from memory. In my case, they were never garbage collected. I looked into it and found out setting the length of an array to 0 doesn't clear the memory (it creates a new one); using `splice` instead does.
> Fix potential memory leak when deleting all cookies

- src/pipeline.js
- test/cookies_test.js
In the event that a redirect invalidates the last cookie, the
cookie store is cleared but the cookie header from the previous
request remains. Since the request pipeline recomputes the cookie
header for each request, this problem can be addressed by
removing the cookie header from the request prior to redirecting.
> Clear cookie header on redirect

- test/script_test.js
Hi Assaf,
I just found out, that inline-script tags that have an invalid attribute-type will still get executed. This behaviour differs from other major browsers. See this snippet:
``` html
<html>
<body>
<script type="true/text/javascript">
console.log('i am executed on zombie/jsdom.');
</script>
</html>
```
will not be executed in other browsers, but on zombie/jsdom. The main problem is, that jQuery uses this trick with prepending `true/`(couldn't believe it either ...) when parsing html, that should be appended to the dom to disable the script tags temporarly.
With the current behaviour inline-script-snippets added to the dom with jQuerys html()-function will be executed twice on zombie but once on browsers (chrome).
I created a test, but I wasn't sure if you want to fix this in your …
> inline scripts with invalid type attribute get executed

- package.json
- src/document.js
This fixes btoa and atob function to match browser's specs. 
It should use binary format not utf8. Current implementation breaks libraries like pako, this fixes it
> btoa atob fix

- README.md
Many of the Browser methods present in Zombie are missing from the README which makes it hard to use as a new user. The descriptions are pulled from `src/index.js`. I'm unsure if this is the best way to organize the API docs but now many more relevant methods are in the README.
> More complete documentation of Browser module API

- src/fetch.js
- test/resources_test.js
Adds a .time field to the request object, as used by resources.js:25 for
calculating the request latency.
> Adds response.time

- README.md
Previously, fill would return this. Now, it returns null or a lazy
Promise. So, the code samples are broken. This fixes the code
samples. See #1176, #1055, and #1054.
> Update README for change to fill method.

- src/document.js
I changed this for myself but thought maybe it could be useful generally. It allows you to listen for `postMessage` in the same way as `alert` or `confirm` - something like
```
Browser.extend(function(browser) {
browser.on('message', function(data) {
console.log('postMessage fired', data);
});
});
```
> Emit on MessageEvent
